//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST65Project {
    
    
    public partial class MidtermExam {
        
        /// <summary>
        /// uxQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder uxQuestions;
        
        /// <summary>
        /// uxTFQ1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ1;
        
        /// <summary>
        /// uxTFQ2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ2;
        
        /// <summary>
        /// uxTFQ3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ3;
        
        /// <summary>
        /// uxTFQ4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ4;
        
        /// <summary>
        /// uxTFQ5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ5;
        
        /// <summary>
        /// uxTFQ6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ6;
        
        /// <summary>
        /// uxTFQ7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ7;
        
        /// <summary>
        /// uxTFQ8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ8;
        
        /// <summary>
        /// uxTFQ9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ9;
        
        /// <summary>
        /// uxTFQ10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.TrueFalseQuestion uxTFQ10;
        
        /// <summary>
        /// uxEssayQ1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ1;
        
        /// <summary>
        /// uxEssayQ2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ2;
        
        /// <summary>
        /// uxEssayQ3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ3;
        
        /// <summary>
        /// uxEssayQ4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ4;
        
        /// <summary>
        /// uxEssayQ5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ5;
        
        /// <summary>
        /// uxEssayQ6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ6;
        
        /// <summary>
        /// uxEssayQ7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.EssayQuestion uxEssayQ7;
        
        /// <summary>
        /// uxMultiQ1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.MultipleChoiceQuestion uxMultiQ1;
        
        /// <summary>
        /// xMultiQ2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.MultipleChoiceQuestion xMultiQ2;
        
        /// <summary>
        /// xMultiQ3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.MultipleChoiceQuestion xMultiQ3;
        
        /// <summary>
        /// xMultiQ4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.MultipleChoiceQuestion xMultiQ4;
        
        /// <summary>
        /// xMultiQ5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.MultipleChoiceQuestion xMultiQ5;
        
        /// <summary>
        /// uxShortQ1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ1;
        
        /// <summary>
        /// uxShortQ2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ2;
        
        /// <summary>
        /// uxShortQ3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ3;
        
        /// <summary>
        /// uxShortQ4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ4;
        
        /// <summary>
        /// uxShortQ5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ5;
        
        /// <summary>
        /// uxShortQ6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ6;
        
        /// <summary>
        /// uxShortQ7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST65Project.ShortTextQuestion uxShortQ7;
        
        /// <summary>
        /// uxSubmitButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button uxSubmitButton;
    }
}
